apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: react-build-{{APP_NAME}}
  namespace: argo
  labels:
    framework: react
    app: {{APP_NAME}}
spec:
  entrypoint: build-and-deploy

  arguments:
    parameters:
    - name: repo-url
      value: "{{REPO_URL}}"
    - name: git-branch
      value: "main"
    - name: git-commit-sha
      value: "{{GIT_SHA}}"
    - name: image-name
      value: "{{REGISTRY}}/{{TENANT}}/{{IMAGE_NAME}}"
    - name: namespace
      value: "{{NAMESPACE}}"
    - name: app-name
      value: "{{APP_NAME}}"
    # Build-time environment variables for React
    - name: react-app-api-url
      value: ""
    - name: public-url
      value: ""

  serviceAccountName: argo-workflow

  templates:
  - name: build-and-deploy
    steps:
    - - name: clone-repo
        template: git-clone

    - - name: install-dependencies
        template: npm-install
        arguments:
          artifacts:
          - name: source
            from: "{{steps.clone-repo.outputs.artifacts.source}}"

    - - name: run-tests
        template: run-tests
        arguments:
          artifacts:
          - name: source
            from: "{{steps.install-dependencies.outputs.artifacts.source}}"

    - - name: build-app
        template: build-react
        arguments:
          artifacts:
          - name: source
            from: "{{steps.run-tests.outputs.artifacts.source}}"

    - - name: build-docker-image
        template: docker-build
        arguments:
          artifacts:
          - name: source
            from: "{{steps.build-app.outputs.artifacts.source}}"

  - name: git-clone
    container:
      image: alpine/git:latest
      workingDir: /workspace
      command: [sh, -c]
      args:
        - |
          git clone {{workflow.parameters.repo-url}} .
          git checkout {{workflow.parameters.git-branch}}
          if [ "{{workflow.parameters.git-commit-sha}}" != "latest" ]; then
            git reset --hard {{workflow.parameters.git-commit-sha}} || echo "⚠️  Commit SHA not found, using HEAD"
          fi
          echo "✓ Cloned repository"
          echo "✓ Branch: {{workflow.parameters.git-branch}}"
          echo "✓ Commit: {{workflow.parameters.git-commit-sha}}"
    outputs:
      artifacts:
      - name: source
        path: /workspace
        archive:
          tar:
            compressionLevel: 1

  - name: npm-install
    inputs:
      artifacts:
      - name: source
        path: /workspace
    container:
      image: node:{{NODE_VERSION}}-alpine
      workingDir: /workspace
      command: [sh, -c]
      args:
        - |
          echo "📦 Installing dependencies..."

          # Detect package manager and install dependencies
          if [ -f package-lock.json ]; then
            echo "Using npm..."
            npm ci
          elif [ -f yarn.lock ]; then
            echo "Using yarn..."
            yarn install --frozen-lockfile
          elif [ -f pnpm-lock.yaml ]; then
            echo "Using pnpm..."
            npm install -g pnpm
            pnpm install --frozen-lockfile
          else
            echo "No lockfile found, using npm install..."
            npm install
          fi

          echo "✓ Dependencies installed"
      resources:
        requests:
          memory: "512Mi"
          cpu: "500m"
        limits:
          memory: "2Gi"
          cpu: "2000m"
    outputs:
      artifacts:
      - name: source
        path: /workspace
        archive:
          tar:
            compressionLevel: 1

  - name: run-tests
    inputs:
      artifacts:
      - name: source
        path: /workspace
    container:
      image: node:{{NODE_VERSION}}-alpine
      workingDir: /workspace
      command: [sh, -c]
      args:
        - |
          echo "🧪 Running tests..."

          # Check if test script exists
          if ! grep -q '"test"' package.json; then
            echo "⚠️  No test script found, skipping tests"
            exit 0
          fi

          # Check if test script is just a placeholder
          if grep -q '"test": "echo' package.json; then
            echo "⚠️  Test script is a placeholder, skipping tests"
            exit 0
          fi

          # Run tests without watch mode
          npm test -- --watchAll=false --passWithNoTests || echo "⚠️  Tests failed but continuing..."
          echo "✓ Tests completed"
      resources:
        requests:
          memory: "512Mi"
          cpu: "500m"
        limits:
          memory: "1Gi"
          cpu: "1000m"
    outputs:
      artifacts:
      - name: source
        path: /workspace
        archive:
          tar:
            compressionLevel: 1

  - name: build-react
    inputs:
      artifacts:
      - name: source
        path: /workspace
    container:
      image: node:{{NODE_VERSION}}-alpine
      workingDir: /workspace
      command: [sh, -c]
      args:
        - |
          echo "🏗️  Building React application..."

          # Set build-time environment variables
          export NODE_ENV=production

          # Set React environment variables if provided
          if [ -n "{{workflow.parameters.react-app-api-url}}" ]; then
            export REACT_APP_API_URL="{{workflow.parameters.react-app-api-url}}"
            export VITE_API_URL="{{workflow.parameters.react-app-api-url}}"
          fi

          if [ -n "{{workflow.parameters.public-url}}" ]; then
            export PUBLIC_URL="{{workflow.parameters.public-url}}"
          fi

          # Build the application
          npm run build

          echo "✓ React build completed"

          # Display build info and detect output directory
          if [ -d build ]; then
            echo "📊 Build output: build/"
            du -sh build
          elif [ -d dist ]; then
            echo "📊 Build output: dist/"
            du -sh dist
          else
            echo "❌ No build output found in build/ or dist/"
            echo "Checking for other possible output directories..."
            find . -maxdepth 2 -type d -name "build" -o -name "dist" -o -name "out"
            exit 1
          fi
      resources:
        requests:
          memory: "1Gi"
          cpu: "1000m"
        limits:
          memory: "4Gi"
          cpu: "2000m"
    outputs:
      artifacts:
      - name: source
        path: /workspace
        archive:
          tar:
            compressionLevel: 1

  - name: docker-build
    inputs:
      artifacts:
      - name: source
        path: /workspace
    container:
      image: gcr.io/kaniko-project/executor:latest
      workingDir: /workspace
      command: [/kaniko/executor]
      args:
        - --dockerfile=/workspace/Dockerfile
        - --context=/workspace
        - --destination={{workflow.parameters.image-name}}:{{workflow.parameters.git-commit-sha}}
        - --destination={{workflow.parameters.image-name}}:latest
        - --cache=true
        - --cache-ttl=24h
        - --compressed-caching=false
        - --snapshotMode=redo
        - --skip-push-permission-check
        - --log-format=text
        - --verbosity=info
        # Pass build args for environment variables
        - --build-arg=REACT_APP_API_URL={{workflow.parameters.react-app-api-url}}
        - --build-arg=VITE_API_URL={{workflow.parameters.react-app-api-url}}
        - --build-arg=PUBLIC_URL={{workflow.parameters.public-url}}
      env:
      - name: DOCKER_CONFIG
        value: /kaniko/.docker
      volumeMounts:
      - name: docker-config
        mountPath: /kaniko/.docker/
      resources:
        requests:
          memory: "512Mi"
          cpu: "500m"
        limits:
          memory: "2Gi"
          cpu: "2000m"

  # Volumes referenced by containers
  volumes:
  - name: docker-config
    secret:
      secretName: scw-registry-secret
      items:
      - key: .dockerconfigjson
        path: config.json
