apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: nextjs-build-{{APP_NAME}}
  namespace: argo
  labels:
    framework: nextjs
    app: {{APP_NAME}}
spec:
  entrypoint: build-and-deploy

  arguments:
    parameters:
    - name: repo-url
      value: "{{REPO_URL}}"
    - name: git-branch
      value: "main"
    - name: git-commit-sha
      value: "{{GIT_SHA}}"
    - name: image-name
      value: "{{REGISTRY}}/{{TENANT}}/{{IMAGE_NAME}}"
    - name: namespace
      value: "{{NAMESPACE}}"
    - name: app-name
      value: "{{APP_NAME}}"

  serviceAccountName: argo-workflow

  volumeClaimTemplates:
  - metadata:
      name: workspace
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 2Gi

  templates:
  - name: build-and-deploy
    steps:
    - - name: clone-repo
        template: git-clone

    - - name: install-dependencies
        template: npm-install

    - - name: run-tests
        template: run-tests

    - - name: build-app
        template: build-nextjs

    - - name: build-docker-image
        template: docker-build

    # Image Updater will detect the new image and update the deployment
    # No need for kubectl update steps

  - name: git-clone
    container:
      image: alpine/git:latest
      workingDir: /workspace
      command: [sh, -c]
      args:
        - |
          git clone {{workflow.parameters.repo-url}} .
          git checkout {{workflow.parameters.git-branch}}
          git reset --hard {{workflow.parameters.git-commit-sha}}
          echo "✓ Cloned repository"
          echo "✓ Branch: {{workflow.parameters.git-branch}}"
          echo "✓ Commit: {{workflow.parameters.git-commit-sha}}"
      volumeMounts:
      - name: workspace
        mountPath: /workspace

  - name: npm-install
    container:
      image: node:18-alpine
      workingDir: /workspace
      command: [sh, -c]
      args:
        - |
          echo "📦 Installing dependencies..."

          if [ -f package-lock.json ]; then
            npm ci --only=production
          else
            npm install --only=production
          fi

          echo "✓ Dependencies installed"
      volumeMounts:
      - name: workspace
        mountPath: /workspace
      resources:
        requests:
          memory: "512Mi"
          cpu: "500m"
        limits:
          memory: "2Gi"
          cpu: "2000m"

  - name: run-tests
    container:
      image: node:18-alpine
      workingDir: /workspace
      command: [sh, -c]
      args:
        - |
          echo "🧪 Running tests..."

          if ! grep -q '"test"' package.json; then
            echo "⚠️  No test script found, skipping tests"
            exit 0
          fi

          npm test || echo "⚠️  Tests failed but continuing..."
          echo "✓ Tests completed"
      volumeMounts:
      - name: workspace
        mountPath: /workspace
      resources:
        requests:
          memory: "512Mi"
          cpu: "500m"
        limits:
          memory: "1Gi"
          cpu: "1000m"

  - name: build-nextjs
    container:
      image: node:18-alpine
      workingDir: /workspace
      command: [sh, -c]
      args:
        - |
          echo "🏗️  Building Next.js application..."

          export NODE_ENV=production
          export NEXT_TELEMETRY_DISABLED=1

          npm run build

          echo "✓ Next.js build completed"

          if [ -d .next ]; then
            echo "📊 Build output size:"
            du -sh .next
          fi
      volumeMounts:
      - name: workspace
        mountPath: /workspace
      resources:
        requests:
          memory: "1Gi"
          cpu: "1000m"
        limits:
          memory: "4Gi"
          cpu: "2000m"

  - name: docker-build
    container:
      image: gcr.io/kaniko-project/executor:v1.9.0
      workingDir: /workspace
      command: [/kaniko/executor]
      args:
        - --dockerfile=/workspace/{{DOCKERFILE_PATH}}
        - --context=/workspace
        - --destination={{workflow.parameters.image-name}}:{{workflow.parameters.git-commit-sha}}
        - --destination={{workflow.parameters.image-name}}:latest
        - --cache=true
        - --cache-ttl=24h
        - --compressed-caching=false
        - --snapshot-mode=redo
        - --log-format=text
        - --verbosity=info
      volumeMounts:
      - name: workspace
        mountPath: /workspace
      - name: docker-config
        mountPath: /kaniko/.docker/
      resources:
        requests:
          memory: "512Mi"
          cpu: "500m"
        limits:
          memory: "2Gi"
          cpu: "2000m"

  # Build complete - Image Updater will handle deployment
  # The workflow only builds and pushes the image
  # ArgoCD Image Updater will:
  # 1. Detect new image tag in registry (polls every 2 minutes)
  # 2. Update the deployment via Kubernetes API
  # 3. ArgoCD will sync the changes

  volumes:
  - name: docker-config
    secret:
      secretName: docker-registry-secret
      items:
      - key: .dockerconfigjson
        path: config.json
